sonar.projectKey=node-login-app
sonar.projectName=Node Login App
sonar.language=js
sonar.sources=app
# Menginstruksikan SonarQube untuk mengecualikan folder public (frontend) dari scanning
sonar.exclusions=app/public/**