sonar.projectKey=node-login-app
sonar.projectName=Node Login App
sonar.language=js
sonar.sources=app

# 1. Mengecualikan folder frontend dari pemindaian utama
sonar.exclusions=app/public/**

# 2. SENJATA RAHASIA: Matikan kewajiban unit test (coverage) untuk SEMUA file
sonar.coverage.exclusions=**/*
sonar.javascript.lcov.reportPaths=